name: Run silencer

on:
  workflow_dispatch:
    # Allow running manually
  schedule:
    # Top of the hour, every hour
    - cron: '0 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Run notification silencer
      run: bundle exec ruby mute.rb
      env:
        OCTOKIT_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
